# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


strategy:
  matrix:
    # Ubuntu
    Ubuntu:
      imageName: 'ubuntu-16.04'
      vcpkgTriplet: 'x64-linux'
    # macOS
#    macOS:
#      imageName: 'macOS-10.14'
#      vcpkgTriplet: 'x64-osx'
    # Windows
    Windows:
      imageName: 'windows-2019'
      vcpkgTriplet: 'x64-windows'

trigger:
  - master

pool:
  vmImage: $(imageName)

steps:
  - script: vcpkg --triplet $(vcpkgTriplet) install boost-program-options boost-iostreams boost-algorithm boost-align
    displayName: 'vcpkg install'

  - task: CMake@1
    inputs:
      workingDirectory: 'build'
      cmakeArgs: '.. -DCMAKE_TOOLCHAIN_FILE=$(VCPKG_INSTALLATION_ROOT)/scripts/buildsystems/vcpkg.cmake'
    displayName: 'CMake'

  - task: CMake@1
    inputs:
      workingDirectory: 'build'
      cmakeArgs: '--build .'
    displayName: 'Build'

  - script: ctest -V
    displayName: 'Test'
    workingDirectory: 'build'




