# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


strategy:
  matrix:
    # Ubuntu
    Ubuntu:
      imageName: 'ubuntu-16.04'
    # macOS
    macOS:
      imageName: 'macOS-10.14'
    # Windows
    Windows:
      imageName: 'windows-2019'

trigger:
  - master

pool:
  vmImage: $(imageName)

steps:
  - script: vcpkg version
    displayName: 'vcpkg version'
#  - task: CMake@1
#    inputs:
#      workingDirectory: 'build'
#      cmakeArgs: '..'
#    displayName: 'CMake'
#
#  - task: CMake@1
#    inputs:
#      workingDirectory: 'build'
#      cmakeArgs: '--build .'
#    displayName: 'Build'
#
#  - script: ctest -V
#    displayName: 'Test'
#    workingDirectory: 'build'




