name: decoding quantities

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: Test decoding quantities can be generated
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64

      - name: install system dependencies
        run: |
          sudo apt install libgmp-dev libmpfr-dev libgsl0-dev default-jdk jblas

      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install cython
          python -m pip install -r TOOLS/PREPARE_DECODING/requirements.txt

      - name: generate & check decoding quantities
        run: |
          bash test_prepare.sh
        working-directory: TOOLS/PREPARE_DECODING/test
