name: macOS unit

on:
  push:
    branches:
      - master

jobs:

  build-and-test:
    name: Unit tests on macOS
    runs-on: macos-latest
    if:  ${{ github.repository == 'PalamaraLab/FastSMC' }}

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          brew install boost libomp eigen

      - name: make build directory
        run: mkdir fastsmc_build_dir

      - name: cmake configure
        run: cmake ..
        working-directory: fastsmc_build_dir

      - name: cmake build
        run: cmake --build . --parallel 2 --target ASMC_unit_tests
        working-directory: fastsmc_build_dir

      - name: cmake test
        run: ctest -j2 -R Asmc_unit_tests --output-on-failure
        working-directory: fastsmc_build_dir
