name: Ubuntu no sse/avx

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: Unit tests with out sse/avx on Ubuntu latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          sudo apt install libboost-python-dev libboost-math-dev libboost-iostreams-dev libboost-program-options-dev
          sudo apt install libeigen3-dev

      - name: make build directory
        run: mkdir asmc_build_dir

      - name: cmake configure
        run: cmake .. -DASMC_FORCE_PURE:BOOL=TRUE
        working-directory: asmc_build_dir

      - name: cmake build
        run: cmake --build . --parallel 2 --target ASMC_unit_tests
        working-directory: asmc_build_dir

      - name: cmake test
        run: ctest -j2 -R Asmc_unit_tests --output-on-failure
        working-directory: asmc_build_dir
