name: Ubuntu continuous test suite

on: [push, pull_request]

jobs:

  build-and-test:
    name: Test on Ubuntu 18.04
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: checkout submodule
        run: git submodule update --init

      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install libboost-python-dev libboost-math-dev libboost-iostreams-dev libboost-program-options-dev
          sudo apt install libeigen3-dev

      - name: make build directory
        run: mkdir asmc_build_dir

      - name: cmake configure
        run: cmake ..
        working-directory: asmc_build_dir

      - name: cmake build
        run: cmake --build . --parallel 2 --target ASMC_unit_tests
        working-directory: asmc_build_dir

      - name: cmake test
        run: ctest -j2 -R Asmc_unit_tests --output-on-failure
        working-directory: asmc_build_dir
