name: Python 3.5 3.8

on: [push, pull_request]

jobs:

  build-and-test:
    name: Unit tests via Python on Ubuntu 18.04
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.8]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: checkout submodule
        run: git submodule update --init

      - name: install dependencies
        run: |
          sudo apt install libboost-python-dev libboost-math-dev libboost-iostreams-dev libboost-program-options-dev
          sudo apt install libeigen3-dev

      - name: install python bindings
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .

      - name: python unit tests
        run: |
          python -m unittest discover ASMC_SRC/TESTS "test_unit*.py"

      - name: python regression tests
        run: |
          python -m unittest ASMC_SRC/TESTS/test_regression.py
