name: Regression test

on: [push, pull_request]

jobs:

  build-and-test:
    name: Regression test on Ubuntu 18.04
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: checkout submodule
        run: git submodule update --init

      - name: install dependencies
        run: |
          sudo apt install libboost-python-dev libboost-math-dev libboost-iostreams-dev libboost-program-options-dev
          sudo apt install libeigen3-dev

      - name: make build directory
        run: mkdir asmc_build_dir

      - name: cmake configure
        run: cmake .. -DCMAKE_BUILD_TYPE=Release
        working-directory: asmc_build_dir

      - name: cmake build
        run: cmake --build . --parallel 2 --target ASMC_regression
        working-directory: asmc_build_dir

      - name: cmake test
        run: ctest -R regression --output-on-failure
        working-directory: asmc_build_dir
